package com.jscn.open.dao;

import com.jscn.open.dao.OpService;
import com.jscn.open.dao.OpServiceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OpServiceMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table OP_SERVICE
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	int countByExample(OpServiceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table OP_SERVICE
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	int deleteByExample(OpServiceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table OP_SERVICE
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table OP_SERVICE
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	int insert(OpService record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table OP_SERVICE
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	int insertSelective(OpService record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table OP_SERVICE
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	List<OpService> selectByExample(OpServiceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table OP_SERVICE
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	OpService selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table OP_SERVICE
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	int updateByExampleSelective(@Param("record") OpService record,
			@Param("example") OpServiceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table OP_SERVICE
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	int updateByExample(@Param("record") OpService record,
			@Param("example") OpServiceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table OP_SERVICE
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	int updateByPrimaryKeySelective(OpService record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table OP_SERVICE
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	int updateByPrimaryKey(OpService record);
}