package com.jscn.open.dao;

import java.util.Date;

public class OpService {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column OP_SERVICE.ID
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column OP_SERVICE.SERVICE_NAME
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	private String serviceName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column OP_SERVICE.METHOD_NAME
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	private String methodName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column OP_SERVICE.URL
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	private String url;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column OP_SERVICE.DESCRIPTION
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column OP_SERVICE.IS_PROTECT
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	private String isProtect;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column OP_SERVICE.STATUS
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column OP_SERVICE.CREATE_BY
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	private String createBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column OP_SERVICE.LAST_UPDATE_TIME
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	private Date lastUpdateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column OP_SERVICE.REMARK
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	private String remark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column OP_SERVICE.ID
	 * @return  the value of OP_SERVICE.ID
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column OP_SERVICE.ID
	 * @param id  the value for OP_SERVICE.ID
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column OP_SERVICE.SERVICE_NAME
	 * @return  the value of OP_SERVICE.SERVICE_NAME
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	public String getServiceName() {
		return serviceName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column OP_SERVICE.SERVICE_NAME
	 * @param serviceName  the value for OP_SERVICE.SERVICE_NAME
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	public void setServiceName(String serviceName) {
		this.serviceName = serviceName == null ? null : serviceName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column OP_SERVICE.METHOD_NAME
	 * @return  the value of OP_SERVICE.METHOD_NAME
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	public String getMethodName() {
		return methodName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column OP_SERVICE.METHOD_NAME
	 * @param methodName  the value for OP_SERVICE.METHOD_NAME
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	public void setMethodName(String methodName) {
		this.methodName = methodName == null ? null : methodName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column OP_SERVICE.URL
	 * @return  the value of OP_SERVICE.URL
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column OP_SERVICE.URL
	 * @param url  the value for OP_SERVICE.URL
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	public void setUrl(String url) {
		this.url = url == null ? null : url.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column OP_SERVICE.DESCRIPTION
	 * @return  the value of OP_SERVICE.DESCRIPTION
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column OP_SERVICE.DESCRIPTION
	 * @param description  the value for OP_SERVICE.DESCRIPTION
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column OP_SERVICE.IS_PROTECT
	 * @return  the value of OP_SERVICE.IS_PROTECT
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	public String getIsProtect() {
		return isProtect;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column OP_SERVICE.IS_PROTECT
	 * @param isProtect  the value for OP_SERVICE.IS_PROTECT
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	public void setIsProtect(String isProtect) {
		this.isProtect = isProtect == null ? null : isProtect.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column OP_SERVICE.STATUS
	 * @return  the value of OP_SERVICE.STATUS
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column OP_SERVICE.STATUS
	 * @param status  the value for OP_SERVICE.STATUS
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	public void setStatus(String status) {
		this.status = status == null ? null : status.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column OP_SERVICE.CREATE_BY
	 * @return  the value of OP_SERVICE.CREATE_BY
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	public String getCreateBy() {
		return createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column OP_SERVICE.CREATE_BY
	 * @param createBy  the value for OP_SERVICE.CREATE_BY
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	public void setCreateBy(String createBy) {
		this.createBy = createBy == null ? null : createBy.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column OP_SERVICE.LAST_UPDATE_TIME
	 * @return  the value of OP_SERVICE.LAST_UPDATE_TIME
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	public Date getLastUpdateTime() {
		return lastUpdateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column OP_SERVICE.LAST_UPDATE_TIME
	 * @param lastUpdateTime  the value for OP_SERVICE.LAST_UPDATE_TIME
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	public void setLastUpdateTime(Date lastUpdateTime) {
		this.lastUpdateTime = lastUpdateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column OP_SERVICE.REMARK
	 * @return  the value of OP_SERVICE.REMARK
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column OP_SERVICE.REMARK
	 * @param remark  the value for OP_SERVICE.REMARK
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}
}