package com.jscn.open.dao;

import java.util.Date;

public class PartnerService {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PARTNER_SERVICE.ID
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PARTNER_SERVICE.PARTNER_ID
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	private Long partnerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PARTNER_SERVICE.SERVICE_ID
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	private Long serviceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PARTNER_SERVICE.LAST_UPDATE_TIME
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	private Date lastUpdateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PARTNER_SERVICE.ID
	 * @return  the value of PARTNER_SERVICE.ID
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PARTNER_SERVICE.ID
	 * @param id  the value for PARTNER_SERVICE.ID
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PARTNER_SERVICE.PARTNER_ID
	 * @return  the value of PARTNER_SERVICE.PARTNER_ID
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	public Long getPartnerId() {
		return partnerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PARTNER_SERVICE.PARTNER_ID
	 * @param partnerId  the value for PARTNER_SERVICE.PARTNER_ID
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	public void setPartnerId(Long partnerId) {
		this.partnerId = partnerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PARTNER_SERVICE.SERVICE_ID
	 * @return  the value of PARTNER_SERVICE.SERVICE_ID
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	public Long getServiceId() {
		return serviceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PARTNER_SERVICE.SERVICE_ID
	 * @param serviceId  the value for PARTNER_SERVICE.SERVICE_ID
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	public void setServiceId(Long serviceId) {
		this.serviceId = serviceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PARTNER_SERVICE.LAST_UPDATE_TIME
	 * @return  the value of PARTNER_SERVICE.LAST_UPDATE_TIME
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	public Date getLastUpdateTime() {
		return lastUpdateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PARTNER_SERVICE.LAST_UPDATE_TIME
	 * @param lastUpdateTime  the value for PARTNER_SERVICE.LAST_UPDATE_TIME
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	public void setLastUpdateTime(Date lastUpdateTime) {
		this.lastUpdateTime = lastUpdateTime;
	}
}