package com.jscn.open.dao;

import com.jscn.open.dao.Partner;
import com.jscn.open.dao.PartnerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PartnerMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table OP_PARTNER
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	int countByExample(PartnerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table OP_PARTNER
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	int deleteByExample(PartnerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table OP_PARTNER
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table OP_PARTNER
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	int insert(Partner record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table OP_PARTNER
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	int insertSelective(Partner record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table OP_PARTNER
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	List<Partner> selectByExample(PartnerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table OP_PARTNER
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	Partner selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table OP_PARTNER
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	int updateByExampleSelective(@Param("record") Partner record,
			@Param("example") PartnerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table OP_PARTNER
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	int updateByExample(@Param("record") Partner record,
			@Param("example") PartnerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table OP_PARTNER
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	int updateByPrimaryKeySelective(Partner record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table OP_PARTNER
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	int updateByPrimaryKey(Partner record);
}