package com.jscn.open.dao;

import java.util.Date;

public class Partner {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column OP_PARTNER.ID
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column OP_PARTNER.PARTNER_NAME
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	private String partnerName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column OP_PARTNER.DESCRIPTION
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column OP_PARTNER.STATUS
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column OP_PARTNER.MD5_KEY
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	private String md5Key;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column OP_PARTNER.IP_LIST
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	private String ipList;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column OP_PARTNER.CREATE_BY
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	private String createBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column OP_PARTNER.LAST_UPDATE_TIME
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	private Date lastUpdateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column OP_PARTNER.REMARK
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	private String remark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column OP_PARTNER.ID
	 * @return  the value of OP_PARTNER.ID
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column OP_PARTNER.ID
	 * @param id  the value for OP_PARTNER.ID
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column OP_PARTNER.PARTNER_NAME
	 * @return  the value of OP_PARTNER.PARTNER_NAME
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	public String getPartnerName() {
		return partnerName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column OP_PARTNER.PARTNER_NAME
	 * @param partnerName  the value for OP_PARTNER.PARTNER_NAME
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	public void setPartnerName(String partnerName) {
		this.partnerName = partnerName == null ? null : partnerName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column OP_PARTNER.DESCRIPTION
	 * @return  the value of OP_PARTNER.DESCRIPTION
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column OP_PARTNER.DESCRIPTION
	 * @param description  the value for OP_PARTNER.DESCRIPTION
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column OP_PARTNER.STATUS
	 * @return  the value of OP_PARTNER.STATUS
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column OP_PARTNER.STATUS
	 * @param status  the value for OP_PARTNER.STATUS
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	public void setStatus(String status) {
		this.status = status == null ? null : status.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column OP_PARTNER.MD5_KEY
	 * @return  the value of OP_PARTNER.MD5_KEY
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	public String getMd5Key() {
		return md5Key;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column OP_PARTNER.MD5_KEY
	 * @param md5Key  the value for OP_PARTNER.MD5_KEY
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	public void setMd5Key(String md5Key) {
		this.md5Key = md5Key == null ? null : md5Key.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column OP_PARTNER.IP_LIST
	 * @return  the value of OP_PARTNER.IP_LIST
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	public String getIpList() {
		return ipList;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column OP_PARTNER.IP_LIST
	 * @param ipList  the value for OP_PARTNER.IP_LIST
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	public void setIpList(String ipList) {
		this.ipList = ipList == null ? null : ipList.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column OP_PARTNER.CREATE_BY
	 * @return  the value of OP_PARTNER.CREATE_BY
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	public String getCreateBy() {
		return createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column OP_PARTNER.CREATE_BY
	 * @param createBy  the value for OP_PARTNER.CREATE_BY
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	public void setCreateBy(String createBy) {
		this.createBy = createBy == null ? null : createBy.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column OP_PARTNER.LAST_UPDATE_TIME
	 * @return  the value of OP_PARTNER.LAST_UPDATE_TIME
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	public Date getLastUpdateTime() {
		return lastUpdateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column OP_PARTNER.LAST_UPDATE_TIME
	 * @param lastUpdateTime  the value for OP_PARTNER.LAST_UPDATE_TIME
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	public void setLastUpdateTime(Date lastUpdateTime) {
		this.lastUpdateTime = lastUpdateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column OP_PARTNER.REMARK
	 * @return  the value of OP_PARTNER.REMARK
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column OP_PARTNER.REMARK
	 * @param remark  the value for OP_PARTNER.REMARK
	 * @mbggenerated  Wed Jun 20 16:46:58 CST 2012
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}
}